# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore: 
      - dependency-name: "@element-plus/components"
      - dependency-name: "@element-plus/eslint-config"
      - dependency-name: "@element-plus/hooks"
      - dependency-name: "@element-plus/theme-chalk"
      - dependency-name: "@element-plus/utils"
      - dependency-name: "element-plus-react"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/internal/eslint-config" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/components" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/element-plus-react" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/hooks" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/theme-chalk" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/utils" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/playground/play" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"