name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Pnpm
        uses: pnpm/action-setup@2
        with:
          version: 7.5.0
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      - name: Run npm scripts
        run: |
          node -v
          pnpm -v
          pnpm install
          pnpm run build:docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
